# src/sar_lm/prompts/templates.py
"""Central repository for all SAR-LM text prompts."""

from textwrap import dedent


FEATURE_SELECTOR_PROMPT = dedent("""
Task: Select the most relevant features to include for audio reasoning.

You are given:
- An audio clip
- The full symbolic features extracted from that audio

Your job is to decide which of the symbolic features (tools) are most relevant for constructing a prompt
to help a large language model (Qwen3-32B) answer reasoning questions about the audio.

The symbolic features were extracted using the following tools:

- Whisper-large: transcribes speech from audio
- Wav2Vec2-based Emotion Model: predicts VAD (valence, arousal, dominance), mapped into symbolic tags ("happy", "angry", etc.)
- PANNs (CNN14): detects general sound events and their timestamps
- MT3: symbolic music transcription model that outputs MIDI files
- Chordino: extracts symbolic chord progressions with start/end times
- Musicnn: predicts high-level music tags such as genre or timbre

After reviewing the symbolic features and listening to the audio:
1. Choose which tools are most useful for reasoning.
2. Decide whether to use a flat symbolic prompt or a natural-language caption.
   - If captioning is better, the final caption will be generated by Gemini 2.5 Pro.

Respond ONLY in the following JSON format:

{
  "selected_features": ["Whisper-large", "PANNs", "MT3"],
  "use_caption": true,
  "comment": "Music and speech both present; caption improves abstraction."
}

Do not include any explanation outside the JSON.
Respond ONLY in valid JSON. Do not use markdown formatting or code blocks.
""").strip()




REASONING_INSTRUCTION_PROMPT = dedent("""
You are a state-of-the-art logical reasoning engine for audio analysis.
Your task is to analyze the provided Audio Context to answer the Question.
First, reason through the evidence step-by-step to determine the single most accurate choice.
Then, provide your final answer in the required format.

- Choose from: {choices_examples}
CRITICAL: Your entire response MUST ONLY be the exact, verbatim text of the correct choice.
Do not add any other words or explanations.
Output exactly the correct choice and nothing else.
""").strip()


CAPTION_PROMPT = dedent("""
You are an audio describer. Concisely capture all important events in this audio that would help a QA system answer questions.
If present, describe:
- Speech (what's said, tone, speaker traits)
- Music (type, mood)
- Background sounds (environment, notable noises)
Keep it brief but informative (1-3 sentences).
""").strip()

CAPTION_PROMPT_MIXED = dedent("""
You are an audio describer. Using both the raw audio and the symbolic features, 
concisely describe all important events that would help a QA system answer questions.

If present, describe:
- Speech (what's said, tone, speaker traits)
- Music (type, mood)
- Background sounds (environment, notable noises)
Keep it brief but informative (1–3 sentences).
""").strip()